In [68]:
import pandas as pd
import numpy as np

In [69]:
df = pd.read_csv('./dataset/train.csv').drop(columns='subject')
testdf = pd.read_csv('./dataset/test.csv').drop(columns='subject')

In [70]:
df.head()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-skewness(),fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",Activity
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.298676,-0.710304,-0.112754,0.030400,-0.464761,-0.018446,-0.841247,0.179941,-0.058627,STANDING
1,0.278419,-0.016411,-0.123520,-0.998245,-0.975300,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,-0.595051,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317,STANDING
2,0.279653,-0.019467,-0.113462,-0.995380,-0.967187,-0.978944,-0.996520,-0.963668,-0.977469,-0.938692,...,-0.390748,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118,STANDING
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.982750,-0.989302,-0.938692,...,-0.117290,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663,STANDING
4,0.276629,-0.016570,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,-0.351471,-0.699205,0.123320,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892,STANDING

In [71]:
df['Activity'].value_counts()

Activity
LAYING                1407
STANDING              1374
SITTING               1286
WALKING               1226
WALKING_UPSTAIRS      1073
WALKING_DOWNSTAIRS     986
Name: count, dtype: int64

In [72]:
df.shape

(7352, 562)

In [73]:
## Perform Logistic Regression 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X_train = df.drop('Activity', axis=1)
y_train = df['Activity']

X_test = testdf.drop('Activity', axis=1)
y_test = testdf['Activity']

le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)

In [74]:
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train_encoded)

LogisticRegression(max_iter=1000)

In [75]:
y_pred = log_reg.predict(X_test)
score = accuracy_score(y_test_encoded, y_pred)
print(score)

0.9606379368849678

In [76]:
def get_duplicate_columns(df):

    duplicate_columns = {}
    seen_columns = {}

    for column in df.columns:

        current_column = df[column]

        try:
            current_column_hash = current_column.values.tobytes()
        except AttributeError:
            current_column_hash = current_column.to_string().encode()

        if current_column_hash in seen_columns:
            first_column = seen_columns[current_column_hash]
            if first_column in duplicate_columns:
                duplicate_columns[first_column].append(column)
            else:
                duplicate_columns[first_column] = [column]
        else:
            seen_columns[current_column_hash] = column
    return duplicate_columns

In [77]:
duplicate_column = get_duplicate_columns(X_train)
duplicate_column

{'tBodyAccMag-mean()': ['tBodyAccMag-sma()',
  'tGravityAccMag-mean()',
  'tGravityAccMag-sma()'],
 'tBodyAccMag-std()': ['tGravityAccMag-std()'],
 'tBodyAccMag-mad()': ['tGravityAccMag-mad()'],
 'tBodyAccMag-max()': ['tGravityAccMag-max()'],
 'tBodyAccMag-min()': ['tGravityAccMag-min()'],
 'tBodyAccMag-energy()': ['tGravityAccMag-energy()'],
 'tBodyAccMag-iqr()': ['tGravityAccMag-iqr()'],
 'tBodyAccMag-entropy()': ['tGravityAccMag-entropy()'],
 'tBodyAccMag-arCoeff()1': ['tGravityAccMag-arCoeff()1'],
 'tBodyAccMag-arCoeff()2': ['tGravityAccMag-arCoeff()2'],
 'tBodyAccMag-arCoeff()3': ['tGravityAccMag-arCoeff()3'],
 'tBodyAccMag-arCoeff()4': ['tGravityAccMag-arCoeff()4'],
 'tBodyAccJerkMag-mean()': ['tBodyAccJerkMag-sma()'],
 'tBodyGyroMag-mean()': ['tBodyGyroMag-sma()'],
 'tBodyGyroJerkMag-mean()': ['tBodyGyroJerkMag-sma()'],
 'fBodyAccMag-mean()': ['fBodyAccMag-sma()'],
 'fBodyBodyAccJerkMag-mean()': ['fBodyBodyAccJerkMag-sma()'],
 'fBodyBodyGyroMag-mean()': ['fBodyBodyGyroMag-sma()'],
 'fBodyBodyGyroJerkMag-mean()': ['fBodyBodyGyroJerkMag-sma()']}

In [78]:
for first_col, dup_cols in duplicate_column.items():
    for col in dup_cols:
        X_train = X_train.drop(columns=col, errors='ignore')
        X_test = X_test.drop(columns=col, errors='ignore')

In [79]:
X_test.columns.value_counts()

angle(Z,gravityMean)      1
tBodyAcc-mean()-X         1
tBodyAcc-mean()-Y         1
tBodyAcc-mean()-Z         1
tBodyAcc-std()-X          1
                         ..
tBodyAcc-arCoeff()-Y,3    1
tBodyAcc-arCoeff()-Y,4    1
tBodyAcc-arCoeff()-Z,1    1
tBodyAcc-arCoeff()-Z,2    1
tBodyAcc-arCoeff()-Z,3    1
Name: count, Length: 540, dtype: int64

In [80]:
from sklearn.feature_selection import VarianceThreshold
sel = VarianceThreshold(threshold=0.05)

In [81]:

sel.fit(X_train)

VarianceThreshold(threshold=0.05)

In [82]:

sum(sel.get_support())

np.int64(349)

In [83]:
# Preserve selected column names from the DataFrame
columns = X_train.columns[sel.get_support()]
columns

Index(['tBodyAcc-std()-X', 'tBodyAcc-std()-Y', 'tBodyAcc-std()-Z',
       'tBodyAcc-mad()-X', 'tBodyAcc-mad()-Y', 'tBodyAcc-mad()-Z',
       'tBodyAcc-max()-X', 'tBodyAcc-max()-Y', 'tBodyAcc-max()-Z',
       'tBodyAcc-min()-X',
       ...
       'fBodyBodyGyroJerkMag-meanFreq()', 'fBodyBodyGyroJerkMag-skewness()',
       'fBodyBodyGyroJerkMag-kurtosis()', 'angle(tBodyAccMean,gravity)',
       'angle(tBodyAccJerkMean),gravityMean)',
       'angle(tBodyGyroMean,gravityMean)',
       'angle(tBodyGyroJerkMean,gravityMean)', 'angle(X,gravityMean)',
       'angle(Y,gravityMean)', 'angle(Z,gravityMean)'],
      dtype='object', length=349)

In [84]:
X_train_selected = sel.transform(X_train)
X_test_selected = sel.transform(X_test)

X_train_selected = pd.DataFrame(
    X_train_selected,
    columns=columns,
    index=X_train.index
)

X_test_selected = pd.DataFrame(
    X_test_selected,
    columns=columns,
    index=X_test.index
)

In [85]:
X_train = X_train_selected
X_test = X_test_selected

In [86]:
X_train.shape

(7352, 349)

In [87]:
X_test.shape

(2947, 349)

In [88]:
import seaborn as sns

In [89]:
corr_matrix = X_train.corr()

In [90]:
corr_matrix

,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,tBodyAcc-max()-Y,tBodyAcc-max()-Z,tBodyAcc-min()-X,...,fBodyBodyGyroJerkMag-meanFreq(),fBodyBodyGyroJerkMag-skewness(),fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)"
tBodyAcc-std()-X,1.000000,0.927461,0.851668,0.998632,0.920888,0.846392,0.980844,0.895217,0.844993,-0.966500,...,-0.065987,0.148034,0.115565,-0.035011,-0.021633,0.018985,-0.024810,-0.371653,0.471065,0.394825
tBodyAcc-std()-Y,0.927461,1.000000,0.895510,0.922803,0.997347,0.894509,0.917366,0.953573,0.884490,-0.937918,...,-0.105621,0.206227,0.176946,-0.020379,-0.012505,-0.008507,-0.014592,-0.380531,0.523600,0.433169
tBodyAcc-std()-Z,0.851668,0.895510,1.000000,0.844469,0.891441,0.997418,0.853884,0.866820,0.937802,-0.860691,...,-0.097978,0.157792,0.126701,-0.006769,-0.020036,-0.018429,-0.006471,-0.345011,0.476006,0.482828
tBodyAcc-mad()-X,0.998632,0.922803,0.844469,1.000000,0.916106,0.839267,0.973216,0.889934,0.838920,-0.962235,...,-0.059972,0.149257,0.117804,-0.042713,-0.021537,0.019389,-0.024951,-0.368191,0.466424,0.390922
tBodyAcc-mad()-Y,0.920888,0.997347,0.891441,0.916106,1.000000,0.891178,0.910411,0.949550,0.879898,-0.933135,...,-0.102908,0.200890,0.172809,-0.023722,-0.012310,-0.012546,-0.012341,-0.377025,0.525081,0.431459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"angle(tBodyGyroMean,gravityMean)",0.018985,-0.008507,-0.018429,0.019389,-0.012546,-0.023525,0.025066,-0.007806,-0.028210,-0.002334,...,-0.026615,0.034514,0.024553,-0.006269,0.009141,1.000000,-0.116001,-0.005853,-0.012313,-0.019903
"angle(tBodyGyroJerkMean,gravityMean)",-0.024810,-0.014592,-0.006471,-0.024951,-0.012341,-0.007231,-0.028871,-0.000297,-0.001207,0.017876,...,0.000102,-0.017937,-0.014865,-0.020823,0.035263,-0.116001,1.000000,0.023995,-0.005869,-0.005656
"angle(X,gravityMean)",-0.371653,-0.380531,-0.345011,-0.368191,-0.377025,-0.347389,-0.384192,-0.372172,-0.346824,0.362847,...,0.087332,-0.086006,-0.079751,0.011880,0.023246,-0.005853,0.023995,1.000000,-0.783848,-0.643655
"angle(Y,gravityMean)",0.471065,0.523600,0.476006,0.466424,0.525081,0.477607,0.480229,0.490324,0.463763,-0.470812,...,-0.100125,0.086993,0.078079,0.001540,-0.012990,-0.012313,-0.005869,-0.783848,1.000000,0.594885
"angle(Z,gravityMean)",0.394825,0.433169,0.482828,0.390922,0.431459,0.479751,0.405023,0.427291,0.419728,-0.393206,...,-0.057468,0.057831,0.052548,-0.003069,-0.017520,-0.019903,-0.005656,-0.643655,0.594885,1.000000

In [91]:
columns = corr_matrix.columns

columns_to_drop = []

for i in range(len(columns)):
    for j in range(i + 1, len(columns)):
        if abs(corr_matrix.loc[columns[i] ,columns[j]]) > 0.95:
            columns_to_drop.append(columns[j])

len(columns_to_drop)

1596

In [92]:
columns_to_drop = set(columns_to_drop)
len(columns_to_drop)

212

In [93]:
X_train.drop(columns= columns_to_drop, axis = 1, inplace = True)
X_test.drop(columns= columns_to_drop, axis = 1, inplace = True)

In [94]:
print("Number of features before SelectKBest:", X_train.shape[1])
print("Number of features in X_test:", X_test.shape[1])
print("Number of selected features:", len(columns))

Number of features before SelectKBest: 137
Number of features in X_test: 137
Number of selected features: 349

# ANOVA

In [95]:
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import SelectKBest

In [96]:
sel = SelectKBest(f_classif, k=100).fit(X_train, y_train_encoded)
columns  = X_train.columns[sel.get_support()]

In [97]:
X_train = sel.transform(X_train)
X_test = sel.transform(X_test)

X_train = pd.DataFrame(X_train, columns=columns)
X_test = pd.DataFrame(X_test, columns=columns)

In [98]:
print(X_train.shape)
print(X_test.shape)

(7352, 100)
(2947, 100)

In [99]:
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train_encoded)

y_pred = log_reg.predict(X_test)

accuracy = accuracy_score(y_test_encoded, y_pred)
print(accuracy)

0.9399389209365456